framework:
  cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include:

    # Redis (recommended for production)
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost

    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu

    # Default: filesystem adapter
    app: cache.adapter.filesystem

    # Namespaced pools use the above "app" backend by default
    pools:
      cache.customer:
        adapter: cache.adapter.filesystem
        default_lifetime: 600
        tags: true
