App\Core\Customer\Application\DTO\TypePatch:
  properties:
    value:
      - Length:
          max: 255

App\Core\Customer\Application\DTO\TypePut:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Core\Customer\Application\DTO\TypeCreate:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Core\Customer\Application\MutationInput\CreateTypeMutationInput:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255

App\Core\Customer\Application\MutationInput\UpdateTypeMutationInput:
  properties:
    value:
      - NotBlank: { message: 'not.blank' }
      - Length:
          max: 255
